In [3]:
import numpy as np

# XOR inputs and expected outputs
X = np.array([[0, 0],
              [0, 1],
              [1, 0],
              [1, 1]])

Y = np.array([[0],
              [1],
              [1],
              [0]])

# Parameters
input_neuron = 2
hidden_neuron = 4
output_neuron = 1
learning_rate = 0.5
epochs = 10000

# Initialize weights and biases (without multiplying by 0.01)
np.random.seed(42)
W1 = np.random.randn(input_neuron, hidden_neuron)
W2 = np.random.randn(hidden_neuron, output_neuron)
b1 = np.zeros((1, hidden_neuron))
b2 = np.zeros((1, output_neuron))

# Activation functions
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return x * (1 - x)

# Training
for i in range(epochs):
    # Forward pass
    hidden_input = np.dot(X, W1) + b1
    hidden_output = sigmoid(hidden_input)

    final_input = np.dot(hidden_output, W2) + b2
    predicted_output = sigmoid(final_input)

    # Backward pass
    error = Y - predicted_output
    d_output = error * sigmoid_derivative(predicted_output)

    error_hidden = d_output.dot(W2.T)
    d_hidden = error_hidden * sigmoid_derivative(hidden_output)

    # Update weights and biases
    W2 += hidden_output.T.dot(d_output) * learning_rate
    b2 += np.sum(d_output, axis=0, keepdims=True) * learning_rate
    W1 += X.T.dot(d_hidden) * learning_rate
    b1 += np.sum(d_hidden, axis=0, keepdims=True) * learning_rate

# Testing
hidden_output = sigmoid(np.dot(X, W1) + b1)
predicted_output = sigmoid(np.dot(hidden_output, W2) + b2)

print("Input:")
print(X)
print("\nExpected Output:")
print(Y)
print("\nPredicted Output:")
print(predicted_output)
print("\nRounded Predicted Output:")
print(np.round(predicted_output))


Input:
[[0 0]
 [0 1]
 [1 0]
 [1 1]]

Expected Output:
[[0]
 [1]
 [1]
 [0]]

Predicted Output:
[[0.01005386]
 [0.98713457]
 [0.98430741]
 [0.0173886 ]]

Rounded Predicted Output:
[[0.]
 [1.]
 [1.]
 [0.]]
